#!/usr/bin/env python3
"""提取 MIT-BIH 正常/异常连续段 → 500Hz float C 数组 (固件回放用)
- 正常段: record 100 (窦性, MLII), 0-45s
- 异常段: record 106 (VEB 密集), 0-45s
输出: include/signal_generator/ecg_replay_data.h
"""
import wfdb
import numpy as np
from scipy.signal import resample_poly
from pathlib import Path

SRC_FS = 360
OUT_FS = 500
DUR_S = 45
# ⚠️ 2026-08-08 单位修正: wfdb p_signal 单位 = mV (数值 ±1.05)。
# 固件信号链期望 V 量级 (模拟器 ±1.2V): 将 mV 数值直接作为 V (×1.0,
# 等效放大 1000 倍: 1.05mV → 1.05V)。原 SCALE=1000 把数值放大 1000 倍
# (1050V), clip ±2.0 后 97.8% 样本平顶 → 信号变形 → AI 全误报。
SCALE = 1.0  # mV 数值 → V 量级

def fetch_segment(record, start_s, dur_s, ch=0):
    rec = wfdb.rdrecord(record, pn_dir='mitdb',
                        sampfrom=int(start_s * SRC_FS),
                        sampto=int((start_s + dur_s) * SRC_FS))
    sig = rec.p_signal[:, ch]  # mV
    # 去均值 (消除直流, 固件 HP 能处理但更干净)
    sig = sig - np.mean(sig)
    # 重采样 360 -> 500
    sig500 = resample_poly(sig, OUT_FS, SRC_FS)
    # mV 数值 → V 量级 (×SCALE), clip 抑制重采样振铃过冲 (固件链路量级 ±2V)
    sig500 = np.clip(sig500 * SCALE, -2.0, 2.0)
    return sig500.astype(np.float32)

def fmt_c_array(name, arr, per_line=8):
    lines = [f'const float {name}[] = {{']
    vals = ', '.join(f'{v:.4f}f' for v in arr)
    # 每行 per_line 个
    parts = [f'{v:.4f}f' for v in arr]
    for i in range(0, len(parts), per_line):
        lines.append('    ' + ', '.join(parts[i:i+per_line]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    print('fetching record 100 (normal)...')
    normal = fetch_segment('100', 0, DUR_S)
    print(f'  {len(normal)} samples @500Hz, amp {np.abs(normal).max():.2f}V')
    print('fetching record 106 (VEB abnormal) @90-135s (VEB 最密集段)...')
    abnormal = fetch_segment('106', 90, DUR_S)
    print(f'  {len(abnormal)} samples @500Hz, amp {np.abs(abnormal).max():.2f}V')

    out = Path(r'C:\Users\cai\OneDrive\Desktop\Fe programme 25261\ecg-programme-tju-flex.electron-master\include\signal_generator\ecg_replay_data.h')
    out.parent.mkdir(parents=True, exist_ok=True)
    header = f"""/* Auto-generated by pc_tools/ecg_dl/make_replay_data.py (2026-08-08)
 * MIT-BIH 连续段回放数据 (wfdb pn_dir=mitdb)
 *   normal  : record 100 (窦性心律), 0-{DUR_S}s, {OUT_FS}Hz, {len(normal)} 样本
 *   abnormal: record 106 (VEB 室早密集), 90-135s, {OUT_FS}Hz, {len(abnormal)} 样本
 * 单位 V (mV×{SCALE:.0f}), float32
 */
#ifndef ECG_REPLAY_DATA_H
#define ECG_REPLAY_DATA_H
#include <stdint.h>

#define ECG_REPLAY_SR        {OUT_FS}
#define ECG_REPLAY_NORMAL_LEN {len(normal)}
#define ECG_REPLAY_ABNORMAL_LEN {len(abnormal)}
"""
    body = fmt_c_array('ecg_replay_normal', normal)
    body += '\n\n'
    body += fmt_c_array('ecg_replay_abnormal', abnormal)
    footer = '\n#endif /* ECG_REPLAY_DATA_H */\n'
    out.write_text(header + body + footer, encoding='utf-8')
    print(f'written: {out} ({out.stat().st_size/1024:.0f} KB)')

if __name__ == '__main__':
    main()
